myreviewsite/game/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('',views.index_view,name = "game_index"),
    path('<int:pk>/detail/',views.DetailGameView.as_view(),name ='detail-game'),
    path('create/',views.CreateGameView.as_view(),name = 'create-game'),
    path('<int:pk>/delete/',views.DeleteGameView.as_view(),name = 'delete-game'),
    path('<int:pk>/update/',views.UpdateGameView.as_view(),name = 'update-game'),
    path('<int:game_id>/review/',views.CreateReviewView.as_view(),name = 'game_review'),
    path('search/',views.post_search,name = 'game_search'),
]

myreviewsite/myreviewsite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('',include('anime.urls')),
    path('game/',include('game.urls')),
]

urlpatterns+=static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

myreviewsite/game/models.py
from django.db import models

# Create your models here.
#ゲームの内容を入れる
CATEGORY = (('シューティング','シューティング'),
            ('アクション','アクション'),
            ('ロールプレイング','ロールプレイング'),
            ('アドベンチャー','アドベンチャー'),
            ('レース','レース'),
            ('シミュレーション','シミュレーション'),
            ('ホラー','ホラー・サスペンス・推理'),
            ('サンドボックス','サンドボックス'),
            ('音楽','音楽'),
            ('テーブル','テーブル'),
            ('その他','その他'),
        )

class Game(models.Model):
    #ゲームの題名
    name = models.CharField(max_length=100)
    #ゲームの概要
    overview = models.TextField()
    #ゲームの画像
    thumbnail = models.ImageField(null = True,blank = True)
    #作者のコメント
    comment = models.TextField(default="無し")
    #ゲームのメインカテゴリー
    main_category = models.CharField(
        max_length=100,
        choices=CATEGORY,
    )
    #ゲームのスコア
    score = models.IntegerField()
    user = models.ForeignKey('auth.User',on_delete=models.CASCADE)
    def __str__(self):
        return self.name

class Game_Review(models.Model):
    game = models.ForeignKey(Game,on_delete=models.CASCADE)
    comment = models.TextField()
    score = models.IntegerField()
    user = models.ForeignKey('auth.User',on_delete=models.CASCADE)
    
    

myreviewsite/game/forms.py
from django import forms

class SearchForm(forms.Form):
    query = forms.CharField(label='検索キーワードを入力', max_length=100)

myreviewsite/game/views.py
from django.shortcuts import render
from django.views.generic import (ListView,
        DetailView,
        CreateView,
        DeleteView,
        UpdateView,
)
from django.urls import reverse,reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Avg
from django.db.models import Q
from django.core.paginator import Paginator

from .consts import ITEM_PER_PAGE

from .models import Game,Game_Review

from .forms import SearchForm


def index_view(request):
    object_list = Game.objects.order_by('-id')
    ranking_list = Game.objects.annotate(avg_score=Avg('game_review__score')).order_by('-avg_score')
    paginator = Paginator(ranking_list,ITEM_PER_PAGE)
    page_number = request.GET.get('page',1)
    page_obj = paginator.page(page_number)
    return render(request,'game/index.html',{'object_list':object_list,'ranking_list':ranking_list,'page_obj':page_obj})


def post_search(request):
    form = SearchForm()
    query = None
    results = []

    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results = Game.objects.filter(
                Q(name__icontains=query) | Q(main_category__icontains=query))

    return render(request, 'game/game_search.html', {'form': form, 'query': query, 'results': results})

# Create your views here.
class AllGameView(ListView):
    template_name = 'game/index.html'
    model = Game

class DetailGameView(DetailView):
    template_name = 'game/game_detail.html'
    model = Game

class CreateGameView(LoginRequiredMixin,CreateView):
    template_name = 'game/game_create.html'
    model = Game
    fields = {'name','overview','thumbnail',
              'main_category','score','user','comment'}
    success_url = reverse_lazy('game_index')

class DeleteGameView(LoginRequiredMixin,DeleteView):
    template_name = 'game/game_delete.html'
    model = Game
    success_url = reverse_lazy('game_index')

class UpdateGameView(LoginRequiredMixin,UpdateView):
    template_name = 'game/game-update.html'
    model = Game
    fields = {'name','overview','thumbnail',
              'main_category','score','comment'}
    success_url = reverse_lazy('game_index')
     
    def get_success_url(self):
        return reverse('detail-game',kwargs={'pk':self.object.id})


class CreateReviewView(LoginRequiredMixin,CreateView):
    model = Game_Review
    fields = ('game','comment','score')
    template_name = 'game/review_form.html'
    
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['game'] = Game.objects.get(pk = self.kwargs['game_id'])
        return context
    
    def form_valid(self,form):
        form.instance.user = self.request.user
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse('detail-game',kwargs={'pk':self.object.game.id})

myreviewsite/templates/game/game-update.html
{%extends 'game_base.html'%}
{%block title%}コンテンツ修正{%endblock%}

{%block content%}
<form method="post" enctype="multipart/form-data" class="p-4 m-4 bg-light border-success rounded form-group">
    {%csrf_token%}
    {{form.as_p}}
    <button type = "submit">編集する</button>
</form>
{%endblock content%}

myreviewsite/templates/game/game_create.html
{%extends 'game_base.html'%}
{%block title%}コンテンツ追加{%endblock%}

{%block content%}
    <form method="post" enctype="multipart/form-data" class = "p-4 m-4 bg-light border-success rounded form-group">
        {%csrf_token%}
        {{form.as_p}}
        <input type="submit" value = "追加する">
    </form>
{%endblock content%}

myreviewsite/templates/game/game_delete.html
{%extends 'game_base.html'%}
{%block title%}コンテンツ削除{%endblock%}

{%block content%}
<form method="post">
    {%csrf_token%}
    <button type = "submit">{{object.name}}を削除する</button>
</form>
{%endblock content%}

myreviewsite/templates/game/game_detail.html
{%extends 'game_base.html'%}
{%block title%}{{object.name}}{%endblock%}
{%block h1%}コンテンツ詳細{%endblock%}

{%block content%}
<div class = "p-4 m-4 bg-light border border-success rounded">
    <h2 class="text-success">{{object.name}}</h2>
    <p>{{object.overview}}</p>
    <div class="border p-4 mb-2">
        {%for review in object.game_review_set.all%}
            <div>
                <div class="px-2">
                    投稿ユーザ:{{review.user.username}}
                    <h6>評価：{{review.score}}点</h6>
                    <p>{{review.comment}}</p>
                </div>
            </div>
        {% endfor %}
    </div>
    <h6 class="card-title">メインカテゴリ：{{object.main_category}}</h6>
    <h6 class="card-title">スコア：{{object.score}}</h6>
    <h6 class="card-title">管理者のレビュー：{{object.comment}}</h6>
    <a href="{%url 'game_index'%}" class="btn btn-primary">ゲーム一覧へ</a>
    <a href="{%url 'game_review' object.pk%}" class="btn btn-primary">コメント・レビューする</a>
    
    {% if request.user.is_superuser %}
    <a href="{%url 'update-game' object.pk%}" class="btn btn-primary">編集する</a>
    <a href="{%url 'delete-game' object.pk%}" class="btn btn-primary">削除する</a>
    {%endif%}
</div>
{%endblock content%}

myreviewsite/templates/game/game_list.html
{%extends 'game_base.html'%}

{%block title%}アニメ一覧{%endblock%}
{%block h1%}アニメ一覧{%endblock%}

{%block content%}
<div class="row">
    <div class="col-9">
        {%for item in object_list%}
        <div class="p-4 m-4 bg-light border border-success border-2 rounded shadow-lg">
            <h2 class="text-success">{{item.name}}</h2>
            <img src="{{item.thumbnail.url}}"  class="img-thumbnail"/>
            <h6>メインカテゴリ:{{item.main_category}}</h6>
            <h5>スコア：{{item.score}}点</h5>
            <div class="mt-3">
                <a href="{%url 'detail-game' item.pk%}" class="btn btn-primary shadow-lg">詳細へ</a>
            </div>
        </div>
    {%endfor%}
    </div>

    <div class="col-3">
        <h2>評価順</h2>
        {%for ranking_game in ranking_list%}
            <div class="p-4 m-4 bg-light border border-success rounded">
                <h3 class="text-success h5">{{ranking_game.name}}</h3>
                <img src="{{ranking_anime.thumbnail.url}}"  class="img-thumbnail">
                <h6>評価:{{ranking_game.avg_score}}点</h6>
                <a href="{% url 'detail-game' ranking_game.id %}">詳細を見る</a>
            </div>
        {%endfor%}
    </div>
</div>
  
{%endblock content%}

myreviewsite/templates/game/game_search.html
{%extends 'game_base.html'%}

{% block content %}
    <h1>ゲームを検索する</h1>
    <h5 class = "mb-4">ゲームのタイトル、メインカテゴリで検索できます。</h5>
    <form method="get">
        {{ form.as_p }}
        <button type="submit" class = "btn btn-primary shadow-lg  mb-4">検索する</button>
    </form>

    {% if query %}
    <h2>"{{ query }}"　の検索結果</h2>
    {% if results %}
    <ul>
        {% for game in results %}
        <div class="p-4 m-4 bg-light border border-success border-2 rounded shadow-lg">
            <h2 class="text-success">{{game.name}}</h2>
            <img src="{{game.thumbnail.url}}" class="img-thumbnail" />
            <h6>メインカテゴリ:{{game.main_category}}</h6>
            <h5>スコア：{{game.score}}点</h5>
            <h5>管理者のレビュー：{{game.comment}}</h5>
            <div class="mt-3">
                <a href="{%url 'detail-game' game.pk%}" class="btn btn-primary shadow-lg">詳細・レビューページへ</a>
            </div>
        </div>
            
        {% endfor %}
    </ul>
    {% else %}
    <p>No results found.</p>
    {% endif %}
    {% endif %}
{% endblock %}

myreviewsite/templates/game/index.html
{%extends 'game_base.html'%}

{%block title%}ゲーム一覧{%endblock%}
{%block h1%}ゲーム一覧{%endblock%}

{%block content%}
<div class="row">
    <div class="col-9">
        {%for item in object_list%}
        <div class="p-4 m-4 bg-light border border-success border-2 rounded shadow-lg">
            <h2 class="text-success">{{item.name}}</h2>
            <img src="{{item.thumbnail.url}}"  class="img-thumbnail"/>
            <h6>メインカテゴリ:{{item.main_category}}</h6>
            <h5>スコア：{{item.score}}点</h5>
            <h5>管理者のレビュー：{{item.comment}}</h5>
            <div class="mt-3">
                <a href="{%url 'detail-game' item.pk%}" class="btn btn-primary shadow-lg">詳細・レビューページへ</a>
            </div>
        </div>
    {%endfor%}
    </div>

    <div class="col-3">
        <h2>評価順</h2>
        {%for ranking_game in page_obj%}
            <div class="p-4 m-4 bg-light border border-success rounded">
                <h3 class="text-success h5">{{ranking_game.name}}</h3>
                <img src="{{ranking_game.thumbnail.url}}"  class="img-thumbnail">
                <h5>評価:{{ranking_game.avg_score|floatformat:2}}点</h5>
                <a href="{% url 'detail-game' ranking_game.id %}">詳細・レビューページへ</a>
            </div>
        {%endfor%}
        {%include 'game/components/pagination.html'%}
    </div>
</div>

{%endblock content%}

myreviewsite/templates/game/review_form.html
{%extends 'game_base.html'%}
{%block title%}コメント・レビュー投稿{%endblock%}

{%block h1%}コメント・レビュー投稿{%endblock%}

{%block content%}
    <form method="post" class="p-4 m-4 bg-light border border-success rounded form-group">
        {%csrf_token%}
        <label>
            コメント・レビュー対象アニメ
        </label>

        <input class="form-control" value = "{{game.name}}" readonly>

        <label>
            コメント本文
        </label>

        <textarea name = "comment" rows = "3" class="form-control"></textarea>

        <label>
            スコア(0~100)
        </label>

        <input class="form-control" name = "score">

        <input type="hidden" name="game" value = "{{game.id}}">
        <button type = "submit" class="btn btn-success mt-4">コメント・レビューを投稿する</button>
    </form>
{%endblock%}